import { prepareEventRegister } from './event-register'

export function on (eventName, selector, options) {
  return (target, {}, descriptor) => {
    const originalMethod = descriptor.value
    const eventRegister = prepareEventRegister(target, originalMethod)

    return eventRegister(eventName, selector, options)
  }
}

/*
const onAbort = eventRegister('abort')
const onAfterprint = eventRegister('afterprint')
const onAnimationEnd = eventRegister('animationend')
const onAnimationIteration = eventRegister('animationiteration')
const onAnimationStart = eventRegister('animationstart')
const onBeforeprint = eventRegister('beforeprint')
const onBeforeunload = eventRegister('beforeunload')
const onBlur = eventRegister('blur')
const onCanplay = eventRegister('canplay')
const onCanplaythrough = eventRegister('canplaythrough')
const onChange = eventRegister('change')
const onClick = eventRegister('click')
const onContextmenu = eventRegister('contextmenu')
const onCopy = eventRegister('copy')
const onCut = eventRegister('cut')
const onDblclick = eventRegister('dblclick')
const onDrag = eventRegister('drag')
const onDragend = eventRegister('dragend')
const onDragenter = eventRegister('dragenter')
const onDragleave = eventRegister('dragleave')
const onDragover = eventRegister('dragover')
const onDragstart = eventRegister('dragstart')
const onDrop = eventRegister('drop')
const onDurationchange = eventRegister('durationchange')
const onEnded = eventRegister('ended')
const onError = eventRegister('error')
const onFocus = eventRegister('focus')
const onFocusin = eventRegister('focusin')
const onFocusout = eventRegister('focusout')
const onFullscreenchange = eventRegister('fullscreenchange')
const onFullscreenerror = eventRegister('fullscreenerror')
const onHashchange = eventRegister('hashchange')
const onInput = eventRegister('input')
const onInvalid = eventRegister('invalid')
const onKeydown = eventRegister('keydown')
const onKeypress = eventRegister('keypress')
const onKeyup = eventRegister('keyup')
const onLoad = eventRegister('load')
const onLoadeddata = eventRegister('loadeddata')
const onLoadedmetadata = eventRegister('loadedmetadata')
const onLoadstart = eventRegister('loadstart')
const onMessage = eventRegister('message')
const onMousedown = eventRegister('mousedown')
const onMouseenter = eventRegister('mouseenter')
const onMouseleave = eventRegister('mouseleave')
const onMousemove = eventRegister('mousemove')
const onMouseover = eventRegister('mouseover')
const onMouseout = eventRegister('mouseout')
const onMouseup = eventRegister('mouseup')
const onOffline = eventRegister('offline')
const onOnline = eventRegister('online')
const onOpen = eventRegister('open')
const onPagehide = eventRegister('pagehide')
const onPageshow = eventRegister('pageshow')
const onPaste = eventRegister('paste')
const onPause = eventRegister('pause')
const onPlay = eventRegister('play')
const onPlaying = eventRegister('playing')
const onProgress = eventRegister('progress')
const onRatechange = eventRegister('ratechange')
const onResize = eventRegister('resize')
const onReset = eventRegister('reset')
const onScroll = eventRegister('scroll')
const onSearch = eventRegister('search')
const onSeeked = eventRegister('seeked')
const onSeeking = eventRegister('seeking')
const onSelect = eventRegister('select')
const onShow = eventRegister('show')
const onStalled = eventRegister('stalled')
const onSubmit = eventRegister('submit')
const onSuspend = eventRegister('suspend')
const onTimeupdate = eventRegister('timeupdate')
const onToggle = eventRegister('toggle')
const onTouchcancel = eventRegister('touchcancel')
const onTouchend = eventRegister('touchend')
const onTouchmove = eventRegister('touchmove')
const onTouchstart = eventRegister('touchstart')
const onTransitionEnd = eventRegister('transitionend')
const onUnload = eventRegister('unload')
const onVolumechange = eventRegister('volumechange')
const onWaiting = eventRegister('waiting')
const onWheel = eventRegister('wheel')
*/
